### ISSUE TITLE
no linux binary

### ISSUE THREAD

**Issue by tcarrondo** [phillbaker/terraform-provider-mailgunv3#1]
I've compiled the binary, do you want to publish it?

**Comment by phillbaker** [comment]
Thanks for opening an issue, looks like i forgot to add that to the travis build. If you'd like to zip it and add it to this issue, i'll add it to https://github.com/phillbaker/terraform-provider-mailgunv3/releases/tag/v0.1.1. Thanks!

**Comment by tcarrondo** [comment]
[terraform-provider-mailgunv3-linux.zip](https://github.com/phillbaker/terraform-provider-mailgunv3/files/2432015/terraform-provider-mailgunv3-linux.zip)

**Comment by phillbaker** [comment]
Thanks! Updated the last release. I'll leave this issue open as a reminder to update the travis build.

**Comment by tcarrondo** [comment]
thanks

**Comment by phillbaker** [comment]
Closed with 584a0acb1967f43cb68f9382e2af31dc6006d0d2.
