### ISSUE TITLE
Support for Terraform 0.12

### ISSUE THREAD

**Issue by kocsismate** [phillbaker/terraform-provider-mailgunv3#11]
Hi,

I wonder if this provider can be used with Terraform 0.12? If not, do you plan to implement support for it in the near future?

Cheers

**Comment by russelltsherman** [comment]
https://github.com/phillbaker/terraform-provider-mailgunv3/pull/13

**Comment by kocsismate** [comment]
Thank you very much! I'll try to test it in the coming weeks.
