### ISSUE TITLE
smtp_password cannot be set anymore

### ISSUE THREAD

**Issue by russelltsherman** [phillbaker/terraform-provider-mailgunv3#12]
experimenting with this.. looks like upstream has made some breaking changes..
looks like the plugin require you to specify smpt_password.. but the api rejects..

```
* mailgunv3_domain.default: UnexpectedResponseError URL=https://api.mailgun.net/v3/domains ExpectedOneOf=[]int{200, 202, 204} Got=400 Error: {
  "message": "smtp_password cannot be set anymore"
}
```

**Comment by phillbaker** [comment]
I think this might be a dupe of https://github.com/phillbaker/terraform-provider-mailgunv3/issues/4#issuecomment-465288098? Can you see if that comment resolves your issue?

**Comment by russelltsherman** [comment]
yes.. most definitely.. thank you very much..
i was not specifying the smpt_password
providing password parameter at 32 chars works around this issue
