### ISSUE TITLE
Error: provider.mailgunv3: fork/exec /tmp/workspace/terraform-provider-mailgunv3: exec format error

### ISSUE THREAD

**Issue by nicoleyson** [phillbaker/terraform-provider-mailgunv3#14]
I got this error message: 
```
Error: provider.mailgunv3: fork/exec /tmp/workspace/terraform-provider-mailgunv3: exec format error
```

Could this be happening because of the binary rename? 
https://github.com/alexissavin/terraform-provider-solidserver/issues/3
This person seems to have experienced similar issues for a different provider, but was able to resolve it by recompiling source. 

That did not resolve it for me. Do you have any ideas, by any chance?  
It had been working a couple days ago 😕 

Additional information:
(tried multiple file permissions - e.g. opening it up completely, 700 etc), I ensured it's definitely there and it's looking for the correct binary 
```
+ terraform-provider-mailgunv3_v0.3.0
  File: terraform-provider-mailgunv3_v0.3.0
  Size: 39238     	Blocks: 80         IO Block: 4096   regular file
Device: 3dh/61d	Inode: 66705       Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-06-12 01:05:28.000000000
Modify: 2019-06-12 01:05:28.000000000
Change: 2019-06-12 01:05:28.000000000
```
```
+ terraform plan '-input=false' '-out=tf-plan'

[31m
[1m[31mError: [0m[0m[1mprovider.mailgunv3: fork/exec terraform-provider-mailgunv3_v0.3.0: no such file or directory[0m
``` 
Estimated Date it Stopped Working: 2-3 days ago?

Terraform Version: `v0.11.13`

**Comment by phillbaker** [comment]
Sorry to hear there are issues. Just to confirm, what version of terraform
and the plugin and OS are you using?

**Comment by phillbaker** [comment]
What OS are you running this on? Are you compiling the provider or using the binary on the release?

**Comment by nicoleyson** [comment]
Thanks for your response! sorry I missed the initial notification!
Linux and I tried both the binary on the release and compiling the provider. 
Terraform Version: v0.11.13

The binary on the release seems to be giving me better results, surprisingly 😆

**Comment by nicoleyson** [comment]
It seems to be indicating it's looking for the correct provider. Nothing else has changed since a couple days ago :/ 

Things I've tried:
- switching the name of the binary to just `mailgunv3` instead of `terraform-provider-mailgunv3_v0.3.0` 
- changing the permissions of the binary `chmod +x` `chmod 700` `chmod 777` 
- bumping the version down to 0.2.0 

Behavior:
- can terraform init and validate with `terraform-provider-mailgunv3_v0.3.0` but not `terraform-provider-mailgunv3` (renamed binary)
- cannot plan with `terraform-provider-mailgunv3_v0.3.0` 

stat before running the plan to ensure it exists:
```
+ stat  <redacted full path to provider>/terraform-provider-mailgunv3_v0.3.0
  File: <redacted full path to provider>/terraform-provider-mailgunv3_v0.3.0
  Size: 33631504  	Blocks: 65688      IO Block: 4096   regular file
Device: 3dh/61d	Inode: 66799       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-06-13 17:21:53.000000000
Modify: 2019-06-13 17:21:50.000000000
Change: 2019-06-13 17:21:52.000000000
``` 
running the plan:
``` 
[Pipeline] sh
+ terraform plan '-input=false' '-out=tf-plan'

provider.mailgunv3: fork/exec <redacted full path to provider>/terraform-provider-mailgunv3_v0.3.0: no such file or directory
``` 

# OS Details 
```
cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.0
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
```
bash-4.4# uname -m
x86_64
```

**Comment by phillbaker** [comment]
Ah, @NicoleYson I think the last detail is the important one. Related to #10 - the current binary on the release page is dynamically compiled for linux, but alpine needs a static build.

I've updated the release to have static builds: https://github.com/phillbaker/terraform-provider-mailgunv3/releases/tag/v0.3.1. Can you try the appropriate file from there or compiling to have a static build locally?

**Comment by nicoleyson** [comment]
Awesome!!! Thanks! I'll try it. 
This is a relief. I was trying all sorts of things like cloning the repository etc to recompile. 🤣

**Comment by nicoleyson** [comment]
YES!!! I think it's working! 😄 Thank you!! 🎉

**Comment by nicoleyson** [comment]
Confirmed working for sure. 
`terraform apply` and everything. Thank you so much for your fast resolution @phillbaker !!! 😄
