### ISSUE TITLE
Publish the provider to Terraform Registry

### ISSUE THREAD

**Issue by invidian** [phillbaker/terraform-provider-mailgunv3#18]
To improve adoption, discoverability and ease of use, especially with recently released Terraform 0.13, it would be great to have this provider published to [Terraform Registry](https://registry.terraform.io/).

To make the process as smooth as possible, ideally following tasks should be completed:
- [ ]  add documentation into `docs` directory in the format described here: https://www.terraform.io/docs/registry/providers/docs.html
- [ ] configure goreleaser to create GitHub releases, as suggested in https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by phillbaker** [comment]
Going to close as this provider is deprecated, please use the original https://www.terraform.io/docs/providers/mailgun/, as per https://github.com/phillbaker/terraform-provider-mailgunv3/issues/19.
