### ISSUE TITLE
support for EU (Europe) region

### ISSUE THREAD

**Issue by tcarrondo** [phillbaker/terraform-provider-mailgunv3#2]
There's no option for choosing between US en EU regions and all resources are added in the US region.

**Comment by phillbaker** [comment]
Good point! It looks like this is documented here: https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions

Is this supported upstream in https://github.com/mailgun/mailgun-go ?

**Comment by tcarrondo** [comment]
Nop, not yet

**Comment by invidian** [comment]
It is now https://github.com/mailgun/mailgun-go/blob/957be9a8aeeb6d50ddf6dbcbce3ba5244ce1c010/mailgun.go#L299.
