### ISSUE TITLE
add resource domain isn't working

### ISSUE THREAD

**Issue by tcarrondo** [phillbaker/terraform-provider-mailgunv3#4]
Adding a domain now returns this message:

```
"message": "smtp_password cannot be set anymore"
```

Need to change this:

```
 "smtp_password": &schema.Schema{
        Type:     schema.TypeString,
        ForceNew: true,
        Required: true,
},
```
to:

```
 "smtp_password": &schema.Schema{
        Type:     schema.TypeString,
        ForceNew: true,
        Optional: true,
},
```

**Comment by tcarrondo** [comment]
@phillbaker , I'll open a PR later today

**Comment by phillbaker** [comment]
Hm, odd that the docs still list this as a parameter, see the fifth box on https://documentation.mailgun.com/en/latest/api-domains.html#example.

```
curl -s --user 'api:YOUR_API_KEY' \
    -X POST \
    https://api.mailgun.net/v3/domains \
    -F name='YOUR_NEW_DOMAIN_NAME' \
    -F smtp_password='supersecretpassword'
```

Edit: Seems similar to https://github.com/terraform-providers/terraform-provider-mailgun/issues/16 though

**Comment by zystem** [comment]
If it is similar to https://github.com/terraform-providers/terraform-provider-mailgun/issues/16
then it is not module bug. This is mailgun documentation bug. Password can not be longer than 32 symbols.
You can check it with https://documentation.mailgun.com/en/latest/api-domains.html#example just by increasing password length in curl.
And as you can see in https://github.com/terraform-providers/terraform-provider-mailgun/issues/16
`resource "random_string" "mailgun_password" {
  length = 64
  special = false
}`
So thats ticked can to be fixed just by replacing
`  length = 64`
with
`  length = 32`
May be yours case have same solution.

**Comment by tcarrondo** [comment]
I just confirmed that @zystem is 100% right!
So I'm closing this issue.
