### ISSUE TITLE
Configure base URL domain

### ISSUE THREAD

**Issue by Bekt** [phillbaker/terraform-provider-mailgunv3#5]
Hi there, the provider doesn't seem to work when there are multiple domains in the account. It is currently hardcoded [here](https://github.com/phillbaker/terraform-provider-mailgunv3/blob/358aa350c4a87cca4d53f85394f5f731a19825a0/config.go#L16).

Is this a known case or is there a workaround?

Ref: https://documentation.mailgun.com/en/latest/api-intro.html#base-url

**Comment by phillbaker** [comment]
Thanks for opening an issue. Are you receiving an error? Can you post any
(sanitized) output to this issue?

**Comment by invidian** [comment]
@Bekt the base URL you referenced seems like a duplicate of #2.

**Comment by Bekt** [comment]
Sorry for the absence -- @invidian this is about the project domain, not base API url.

It's been almost three months (lol), but back then I did change the code and recompiled to find the root issue. I got distracted and didn't get far unfortunately however I don't think the issue I was facing was directly related to the project domain. I will close this issue since I don't have extra information.
